# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usbhid"
    "usb_storage"
    "sd_mod"
    "cryptd"
    "amdgpu"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # !!! cryptkey must be done first, and the list seems to be
  # alphabetically sorted, so take care that cryptroot / cryptswap,
  # whatever you name them, come after cryptkey.
  boot.initrd.luks.devices = {
    cryptkey = {
      device = "/dev/disk/by-uuid/bfa6fdc4-aa19-4908-b4d9-10b1d8021706";
    };

    cryptroot = {
      allowDiscards = true;
      device = "/dev/disk/by-uuid/497d160d-cd6d-4355-96bb-47eaf8ef7ff8";
      keyFile = "/dev/mapper/cryptkey";
      keyFileSize = 8192;
    };

    cryptswap = {
      allowDiscards = true;
      device = "/dev/disk/by-uuid/89d44679-7e68-4b6e-8f02-32c51ec48e07";
      keyFile = "/dev/mapper/cryptkey";
      keyFileSize = 8192;
    };
  };

  boot.initrd.postDeviceCommands = lib.mkAfter ''
    cryptsetup close cryptkey
  '';

  fileSystems = {
    "/" = {
      device = "styx/local/root";
      fsType = "zfs";
    };
    "/boot" = {
      device = "/dev/disk/by-uuid/FB5A-020D";
      fsType = "vfat";
      options = [
        "noatime"
        "umask=0077"
      ];
    };
    "/empty/user" = {
      device = "styx/persist/user";
      fsType = "zfs";
    };
    "/home/ivan" = {
      device = "styx/persist/user/ivan";
      fsType = "zfs";
    };
    "/home/ivan/books" = {
      device = "styx/persist/user/ivan/books";
      fsType = "zfs";
    };
    "/home/ivan/vm" = {
      device = "styx/persist/user/ivan/vm";
      fsType = "zfs";
    };
    "/nix" = {
      device = "styx/local/nix";
      fsType = "zfs";
    };
    "/persist" = {
      device = "styx/persist/system";
      fsType = "zfs";
      neededForBoot = true;
    };
    "/scratch" = {
      device = "styx/local/scratch";
      fsType = "zfs";
    };
    "/var" = {
      device = "styx/persist/var";
      fsType = "zfs";
    };
  };

  swapDevices = [
    {
      device = "/dev/mapper/cryptswap";
    }
  ];

  # Bring back previous font look: https://github.com/NixOS/nixpkgs/issues/222805
  fonts.packages = [
    pkgs.font-misc-misc
  ];
}
