name: "Test"
on:
  pull_request:
  push:
    branches-ignore:
      # Don't run twice on automation updates, rely on pull_request hook
      - 'automation/**'
      - 'dependabot/**'
jobs:
  tests:
    strategy:
      # Allow other jobs to finish building and cache properly before bailing
      fail-fast: false
      matrix:
        include:
          - os: macos-12
          - os: ubuntu-latest
          - os: ubuntu-latest
            qemuPlatforms: "arm64"
            systemOverride: "--argstr system aarch64-linux"
            extraPlatforms: "aarch64-linux"

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        extra_nix_config: |
          extra-platforms = ${{ matrix.extraPlatforms }}

    - uses: cachix/cachix-action@v12
      with:
        name: ipetkov
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'

    - name: add nix-community cache
      run: cachix use nix-community

    - name: install QEMU/binfmt
      if: ${{ matrix.qemuPlatforms != '' }}
      uses: docker/setup-qemu-action@v2
      with:
        image: tonistiigi/binfmt:latest
        platforms: ${{ matrix.qemuPlatforms }}

    - name: build package definitions
      run: nix run .#nix-build-uncached -- ${{ matrix.systemOverride }} ./ci/packages.nix

    - name: build home-manager configurations
      run: nix run .#nix-build-uncached -- ${{ matrix.systemOverride }} ./ci/homeConfigurations.nix

    - name: build system definitions
      run: nix run .#nix-build-uncached -- ${{ matrix.systemOverride }} ./ci/systems.nix
