name: Update flake dependencies

on:
  schedule:
    - cron: '0 16 * * 5'
  workflow_dispatch: # for allowing manual triggers of the workflow

permissions:
  contents: read

jobs:
  update-and-push-deps:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v24
    - uses: cachix/cachix-action@v13
      with:
        name: ipetkov
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - name: add nix-community cache
      run: cachix use nix-community
    - name: Update flake.lock
      id: flakeupdate
      uses: DeterminateSystems/update-flake-lock@v20
      with:
        token: ${{ secrets.PAT_FLAKE_UPDATE }}
        branch: "automation/flake-update"
        pr-title: "Update flake.lock"
        pr-labels: |
          automated
          dependencies
          flake update
    - name: Enable Pull Request Automerge
      run: gh pr merge --squash --delete-branch --auto ${{ steps.flakeupdate.outputs.pull-request-number }}
      env:
        GH_TOKEN: ${{ secrets.PAT_FLAKE_UPDATE }}
