name: Update flake dependencies

on:
  schedule:
    - cron: '0 16 * * 5'
  workflow_dispatch: # for allowing manual triggers of the workflow

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v23
    - uses: cachix/cachix-action@v12
      with:
        name: ipetkov
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - name: add nix-community cache
      run: cachix use nix-community
    - name: update flake.lock
      run: nix flake update
    # Use custom app token to be more secure
    - uses: tibdex/github-app-token@v2
      id: generate-token
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.APP_PRIVATE_KEY }}
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ steps.generate-token.outputs.token }}
        commit-message: "flake: update dependencies"
        title: "[automation] update flake dependencies"
        branch: "automation/update-flake-dependencies"
