name: Update flake dependencies

on:
  schedule:
    - cron: '0 13 * * 5'
  workflow_dispatch: # for allowing manual triggers of the workflow

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  update-and-push-deps:
    name: update and push deps
    runs-on: ubuntu-latest
    environment: flake-update
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false
    - uses: cachix/install-nix-action@a49548c11d9846ad46ecc0115273879b045f001c # v31.10.7
    - uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
      with:
        name: ipetkov
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - name: Update flake.lock
      id: flakeupdate
      uses: DeterminateSystems/update-flake-lock@834c491b2ece4de0bbd00d85214bb5e83b4da5c6 # v28
      with:
        token: ${{ secrets.PAT_FLAKE_UPDATE }}
        branch: "automation/flake-update"
        pr-title: "Update flake.lock"
        pr-labels: |
          automated
          dependencies
          flake update
    - name: Enable Pull Request Automerge
      run: gh pr merge --squash --delete-branch --auto "${PR_NUMBER}"
      env:
        GH_TOKEN: ${{ secrets.PAT_FLAKE_UPDATE }}
        PR_NUMBER: ${{ steps.flakeupdate.outputs.pull-request-number }}
